language: python # => 1
    python: # => 2
      - "3.7.5"
    services: # => 3
      - posfresql
    env: # => 4
      -DJANGO=1.8 DB=posfresql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - psql -c 'create database ledenbestand;' -U postgres
    script: # => 7
      - python manage.py test